//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.ASISTENCIACARRETERA = new HashSet<ASISTENCIACARRETERA>();
            this.BASTIDORESTECHO = new HashSet<BASTIDORESTECHO>();
            this.CUBIERTAS = new HashSet<CUBIERTAS>();
            this.REMOLQUE = new HashSet<REMOLQUE>();
            this.ALFOMBRAS = new HashSet<ALFOMBRAS>();
            this.ENTRETENIMIENTO = new HashSet<ENTRETENIMIENTO>();
            this.PEDALES = new HashSet<PEDALES>();
            this.PERILLASCAMBIO = new HashSet<PERILLASCAMBIO>();
            this.SUSPENCION = new HashSet<SUSPENCION>();
            this.TERMOSTATO = new HashSet<TERMOSTATO>();
            this.ALTERNADORES = new HashSet<ALTERNADORES>();
            this.FILTRODEAIRE = new HashSet<FILTRODEAIRE>();
            this.DIRECCION1 = new HashSet<DIRECCION>();
            this.FILTROCOMBUSTIBLE = new HashSet<FILTROCOMBUSTIBLE>();
            this.ENCENDIDO = new HashSet<ENCENDIDO>();
            this.FILTROACEITE = new HashSet<FILTROACEITE>();
            this.FRENOS = new HashSet<FRENOS>();
            this.FAJASYMANGUERAS = new HashSet<FAJASYMANGUERAS>();
            this.LUCES = new HashSet<LUCES>();
            this.BUJIAS = new HashSet<BUJIAS>();
            this.RADIADORES = new HashSet<RADIADORES>();
        }
    
        public int id_proveedor { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string CODIGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASISTENCIACARRETERA> ASISTENCIACARRETERA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASTIDORESTECHO> BASTIDORESTECHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUBIERTAS> CUBIERTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REMOLQUE> REMOLQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALFOMBRAS> ALFOMBRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRETENIMIENTO> ENTRETENIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDALES> PEDALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERILLASCAMBIO> PERILLASCAMBIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSPENCION> SUSPENCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TERMOSTATO> TERMOSTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTERNADORES> ALTERNADORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILTRODEAIRE> FILTRODEAIRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCION> DIRECCION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILTROCOMBUSTIBLE> FILTROCOMBUSTIBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCENDIDO> ENCENDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILTROACEITE> FILTROACEITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRENOS> FRENOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAJASYMANGUERAS> FAJASYMANGUERAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUCES> LUCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUJIAS> BUJIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADIADORES> RADIADORES { get; set; }
    }
}
